const depositABI = [
  {
    "type":"constructor",
    "stateMutability":"nonpayable",
    "inputs":[
      {
        "type":"address",
        "name":"_token",
        "internalType":"address"
      }
    ]
  },
  {
    "type":"event",
    "name":"DepositEvent",
    "inputs":[
      {
        "type":"bytes",
        "name":"pubkey",
        "internalType":"bytes",
        "indexed":false
      },
      {
        "type":"bytes",
        "name":"withdrawal_credentials",
        "internalType":"bytes",
        "indexed":false
      },
      {
        "type":"bytes",
        "name":"amount",
        "internalType":"bytes",
        "indexed":false
      },
      {
        "type":"bytes",
        "name":"signature",
        "internalType":"bytes",
        "indexed":false
      },
      {
        "type":"bytes",
        "name":"index",
        "internalType":"bytes",
        "indexed":false
      }
    ],
    "anonymous":false
  },
  {
    "type":"event",
    "name":"Paused",
    "inputs":[
      {
        "type":"address",
        "name":"account",
        "internalType":"address",
        "indexed":false
      }
    ],
    "anonymous":false
  },
  {
    "type":"event",
    "name":"Unpaused",
    "inputs":[
      {
        "type":"address",
        "name":"account",
        "internalType":"address",
        "indexed":false
      }
    ],
    "anonymous":false
  },
  {
    "type":"function",
    "stateMutability":"nonpayable",
    "outputs":[

    ],
    "name":"batchDeposit",
    "inputs":[
      {
        "type":"bytes",
        "name":"pubkeys",
        "internalType":"bytes"
      },
      {
        "type":"bytes",
        "name":"withdrawal_credentials",
        "internalType":"bytes"
      },
      {
        "type":"bytes",
        "name":"signatures",
        "internalType":"bytes"
      },
      {
        "type":"bytes32[]",
        "name":"deposit_data_roots",
        "internalType":"bytes32[]"
      }
    ]
  },
  {
    "type":"function",
    "stateMutability":"nonpayable",
    "outputs":[

    ],
    "name":"claimTokens",
    "inputs":[
      {
        "type":"address",
        "name":"_token",
        "internalType":"address"
      },
      {
        "type":"address",
        "name":"_to",
        "internalType":"address"
      }
    ]
  },
  {
    "type":"function",
    "stateMutability":"nonpayable",
    "outputs":[

    ],
    "name":"deposit",
    "inputs":[
      {
        "type":"bytes",
        "name":"pubkey",
        "internalType":"bytes"
      },
      {
        "type":"bytes",
        "name":"withdrawal_credentials",
        "internalType":"bytes"
      },
      {
        "type":"bytes",
        "name":"signature",
        "internalType":"bytes"
      },
      {
        "type":"bytes32",
        "name":"deposit_data_root",
        "internalType":"bytes32"
      },
      {
        "type":"uint256",
        "name":"stake_amount",
        "internalType":"uint256"
      }
    ]
  },
  {
    "type":"function",
    "stateMutability":"view",
    "outputs":[
      {
        "type":"bytes",
        "name":"",
        "internalType":"bytes"
      }
    ],
    "name":"get_deposit_count",
    "inputs":[

    ]
  },
  {
    "type":"function",
    "stateMutability":"view",
    "outputs":[
      {
        "type":"bytes32",
        "name":"",
        "internalType":"bytes32"
      }
    ],
    "name":"get_deposit_root",
    "inputs":[

    ]
  },
  {
    "type":"function",
    "stateMutability":"nonpayable",
    "outputs":[
      {
        "type":"bool",
        "name":"",
        "internalType":"bool"
      }
    ],
    "name":"onTokenTransfer",
    "inputs":[
      {
        "type":"address",
        "name":"",
        "internalType":"address"
      },
      {
        "type":"uint256",
        "name":"stake_amount",
        "internalType":"uint256"
      },
      {
        "type":"bytes",
        "name":"data",
        "internalType":"bytes"
      }
    ]
  },
  {
    "type":"function",
    "stateMutability":"nonpayable",
    "outputs":[

    ],
    "name":"pause",
    "inputs":[

    ]
  },
  {
    "type":"function",
    "stateMutability":"view",
    "outputs":[
      {
        "type":"bool",
        "name":"",
        "internalType":"bool"
      }
    ],
    "name":"paused",
    "inputs":[

    ]
  },
  {
    "type":"function",
    "stateMutability":"view",
    "outputs":[
      {
        "type":"address",
        "name":"",
        "internalType":"contract IERC20"
      }
    ],
    "name":"stake_token",
    "inputs":[

    ]
  },
  {
    "type":"function",
    "stateMutability":"pure",
    "outputs":[
      {
        "type":"bool",
        "name":"",
        "internalType":"bool"
      }
    ],
    "name":"supportsInterface",
    "inputs":[
      {
        "type":"bytes4",
        "name":"interfaceId",
        "internalType":"bytes4"
      }
    ]
  },
  {
    "type":"function",
    "stateMutability":"nonpayable",
    "outputs":[

    ],
    "name":"unpause",
    "inputs":[

    ]
  },
  {
    "type":"function",
    "stateMutability":"view",
    "outputs":[
      {
        "type":"bytes32",
        "name":"",
        "internalType":"bytes32"
      }
    ],
    "name":"validator_withdrawal_credentials",
    "inputs":[
      {
        "type":"bytes",
        "name":"",
        "internalType":"bytes"
      }
    ]
  }
]

export default depositABI
