name: Automatic Deployment to Dev/Staging

on:
  # Launches for pushes to main or dev
  push:
    branches:
      - main
      - dev

env:
  NEXT_PUBLIC_WC_PROJECT_ID: ${{ secrets.DEV_WC_PROJECT_ID }}

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install
        run: |
          rm -rf .cache
          rm -rf build
          yarn config set cache-folder .yarn
          yarn install
          pip install awscli --upgrade --user

      - name: Build App
        run: yarn update-deposits && yarn build

      - name: Configure AWS Development credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ( github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' )
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_DEFAULT_REGION }}

      # Script to deploy to development environment
      - name: 'Deploy to S3: Development'
        if: github.ref == 'refs/heads/dev'
        run: |
          aws s3 sync build/ s3://${{ secrets.DEV_BUCKET_NAME }}/dev --exclude "*.html" --cache-control max-age=0,no-cache,no-store,public
          aws s3 sync build/ s3://${{ secrets.DEV_BUCKET_NAME }}/dev --exclude "*" --include "*.html" --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
          aws s3 sync data/ s3://${{ secrets.DEV_BUCKET_NAME }}/dev

      # Script to deploy to staging environment
      - name: 'Deploy to S3: Staging'
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync build/ s3://${{ secrets.DEV_BUCKET_NAME }}/main --exclude "*.html" --cache-control max-age=0,no-cache,no-store,public
          aws s3 sync build/ s3://${{ secrets.DEV_BUCKET_NAME }}/main --exclude "*" --include "*.html" --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
          aws s3 sync data/ s3://${{ secrets.DEV_BUCKET_NAME }}/main